LPI_FILE_NAME = "BBAS_LPI "
RFP_FILE_NAME = "BBAS_RFP "
BANK_FILE_NAME = "BBAS_BANK "
INVOICE_FILE_NAME = "BBAS_INV "
DELIVERY_FILE_NAME = "BBAS_DEL "
FINAL_COMPILED_FILE_NAME = "BBAS_RFP_final"

OUTPUT_DIR_NAME = "outputs"
CONVERTED_IMAGE_DIR_NAME = "converted_images"

VALID_FILE_EXTENSION = [".pdf", ".png", ".jpeg", ".jpg"]

